Update dast-zap-scan.yml

diff --git a/.github/workflows/dast-zap-scan.yml b/.github/workflows/dast-zap-scan.yml
--- a/.github/workflows/dast-zap-scan.yml
+++ b/.github/workflows/dast-zap-scan.yml
@@ -20,16 +20,23 @@ jobs:
         run: |
           sudo apt-get update
           sudo apt-get install -y openjdk-11-jdk
-          # Download ZAP
-          curl -sS https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2.11.1_Unix.tar.gz -o zap.tar.gz
-          # Verify the file was downloaded correctly
-          ls -lh zap.tar.gz
-          # Extract the archive
-          tar -xvf zap.tar.gz
-          # Check if the folder is extracted correctly
-          ls -lh
-          sudo mv zap-2.11.1 /opt/zap
-          sudo ln -s /opt/zap/zap.sh /usr/local/bin/zap
+          # Install ZAP directly using apt (if available)
+          sudo apt-get install -y zaproxy
+          
+          # If installation via apt is not successful, fall back to tar method
+          if ! command -v zap &> /dev/null
+          then
+            echo "ZAP not found, downloading from GitHub..."
+            curl -sS https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2.11.1_Unix.tar.gz -o zap.tar.gz
+            # Check if the file was downloaded correctly
+            ls -lh zap.tar.gz
+            # Extract the archive
+            tar -xvf zap.tar.gz
+            # Check if the folder is extracted correctly
+            ls -lh
+            sudo mv zap-2.11.1 /opt/zap
+            sudo ln -s /opt/zap/zap.sh /usr/local/bin/zap
+          fi
 
       - name: Run ZAP Full Scan and print result in console
         run: |
